---
title: "TEST2 - INFO911-Project-Group19"
author: "Tajveer Singh Dhesi"
date: "2024-04-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(dplyr)
library(rpart)
library(leaps)

```



## Pre-Processing
```{r}
aircon = read.csv("ac_2024_04_30.csv")
aircon = aircon <- subset(aircon, 
                           grepl("Available", ac_data$Availability.Status) & 
                             grepl("Australia", ac_data$Sold_in))
aircon <- replace(aircon,aircon == "-", "N/A")
aircon <- replace(aircon, aircon == "", "N/A")
all_cols = colnames(aircon)


numeric_cols <- sapply(aircon, function(x) all(grepl("^(-?\\d+\\.?\\d*|N/A|-)$", x)))

# Convert identified columns to numeric
for (x in all_cols){
  if (numeric_cols[x] == TRUE){
    aircon[[x]] = as.numeric(aircon[[x]])
  }
}
aircon <- replace(aircon, aircon == "-" | aircon == "" | aircon == "N/A", NA)
```

```{r}
clean = function(dataSet, str){
  dataSet = aircon %>% select(all_of(features))
  dataSet <- replace(dataSet, dataSet == "0" | dataSet == 0 | dataSet == 0.0, NA)
  for (i in colnames(dataSet)) {
    if (sum(is.na(dataSet[i]))/nrow(dataSet) != 0){
      if (i != str){
        dataSet = dataSet %>% select(-one_of(i))
      }
    }
  }
  dataSet <- mutate_if(dataSet, is.character, as.factor)
}
```
```{r}
features = NULL
toRemove = c("ApplStandard",	"MEPSComp",	"N.Standard", "Family.Name", "Sold_in",	"Submit_ID",	"SubmitStatus", "Demand.Response.1", "Demand.Response.2","Demand.Response.4","Demand.Response.5","Demand.Response.6","Demand.Response.7", "Demand.Response.Capability",	"Product.Class", "Demand.Response.1",	"Availability.Status",	"Product.Website",	"Representative.Brand.URL",	"Registration.Number", "Country", "Model_No", "ExpDate", "Type", "Phase", "sri2010_heat", "sri2010_cool", "Star2010_Cool", "Star2010_Heat", "Brand", "Have_water_tank")

temp = aircon %>% select(-all_of(toRemove))
features = colnames(temp)

features = append(features, "sri2010_heat")

# aircon_subset_heating = aircon %>% select(all_of(features))
# aircon_subset_heating <- replace(aircon_subset_heating, aircon_subset_heating == "0" | aircon_subset_heating == 0 | aircon_subset_heating == 0.0, NA)
# for (i in colnames(aircon_subset_heating)) {
#   if (sum(is.na(aircon_subset_heating[i]))/nrow(aircon_subset_heating) != 0){
#     if (i != "sri2010_heat"){
#       aircon_subset_heating = aircon_subset_heating %>% select(-one_of(i))
#     }
#   }
# }
# aircon_subset_heating <- mutate_if(aircon_subset_heating, is.character, as.factor)
# 
# aircon_subset_heating = aircon_subset_heating %>% mutate()
aircon_subset_heating = clean(aircon_subset_heating, "sri2010_heat")

aircon_known_heating = subset(aircon_subset_heating, !is.na(aircon_subset_heating["sri2010_heat"]))
aircon_unknown_heating = subset(aircon_subset_heating, is.na(aircon_subset_heating["sri2010_heat"]))

```
```{r}
features = features[features != "sri2010_heat"]
features = append(features, "sri2010_cool")


aircon_subset_cooling = clean(aircon_subset_cooling, "sri2010_cool")

aircon_known_cooling = subset(aircon_subset_cooling, !is.na(aircon_subset_cooling["sri2010_cool"]))
aircon_unknown_cooling = subset(aircon_subset_cooling, is.na(aircon_subset_cooling["sri2010_cool"]))
```

```{r}
# aircon$EERtestAvg cooling
# aircon$COPtestAvg heating
#Lino, Thapa
# aircon_known_heating_eff = 
# aircon_unknown_heating_eff = 
# 
# aircon_known_cooling_eff = 
# aircon_unknown_cooling_eff = 
```

## Modelling

```{r}
#Multiple Linear Regression Heating

#lm.fit = lm(sri2010_heat~., data = aircon_known_heating)

# step.fit = step(lm.fit, direction = "both", k = log(nrow(aircon_known_heating)))
# summary(step.fit)

reg_model <- regsubsets(sri2010_heat~., data = aircon_known_heating)

reg_model[[3]]
l = summary(reg_model)$which[3,]

lm_best_model <- lm(sri2010_heat ~ Rated.AEER + Refrigerant + Configuration2, data = aircon_known_heating)
summary(lm_best_model)

residuals = step.fit$residuals
fitted_values = step.fit$fitted.values

plot(fitted_values, residuals/sqrt(var(residuals)), main = "Standardized Residuals vs Fitted Values", 
     xlab = "Fitted Values", ylab = "Standardized Residuals")
abline(h = 0, col = "red", lty = 2)

qqnorm(residuals)
qqline(residuals)

predictions <- predict(step.fit, newdata = aircon_known_heating)
max(predictions)
# Calculate Mean Squared Error (MSE)
mse <- mean((aircon_known_heating$sri2010_heat - predictions)^2)
summary(aircon_known_heating$sri2010_heat)
```

```{r}
#Regression Tree Heating

fit.tree <- rpart(sri2010_heat~., data = aircon_known_heating)
plot(fit.tree)
text(fit.tree, digits = 4)
predictions <- predict(fit.tree, newdata = aircon_known_heating)
# Calculate Mean Squared Error (MSE)
mse <- mean((aircon_known_heating$sri2010_heat - predictions)^2)
summary(aircon_known_heating$sri2010_heat)
sd(aircon_known_heating$sri2010_heat)
```

```{r}
#Multiple Linear Regression Cooling
reg_model <- regsubsets(sri2010_cool~., data = aircon_known_cooling)

summary(reg_model)$cp
summary(reg_model)$which[4,]
lm_best_model = lm(sri2010_cool~C.Total.Cool.Rated + Configuration2 + Rated.AEER + Refrigerant, data = aircon_known_cooling)
summary(lm.fit)




#lm.fit = lm(sri2010_cool~., data = aircon_known_cooling)

# step.fit = step(lm.fit, direction = "both", k = log(nrow(aircon_known_cooling)))
# summary(step.fit)

residuals = lm_best_model$residuals
fitted_values = lm_best_model$fitted.values

plot(fitted_values, residuals/sqrt(var(residuals)), main = "Standardized Residuals vs Fitted Values", 
     xlab = "Fitted Values", ylab = "Standardized Residuals")
abline(h = 0, col = "red", lty = 2)

qqnorm(residuals)
qqline(residuals)

predictions <- predict(lm_best_model, newdata = aircon_known_cooling)
# Calculate Mean Squared Error (MSE)
mse <- mean((aircon_known_cooling$sri2010_cool - predictions)^2)
summary(aircon_known_cooling$sri2010_cool)
```

```{r}
#Regression Tree Cooling
fit.tree <- rpart(sri2010_cool~., data = aircon_known_cooling)
plot(fit.tree)
text(fit.tree, digits = 4)
predictions <- predict(fit.tree, newdata = aircon_known_cooling)
# Calculate Mean Squared Error (MSE)
mse <- mean((aircon_known_cooling$sri2010_cool - predictions)^2)
summary(aircon_known_cooling$sri2010_cool)
sd(aircon_known_cooling$sri2010_cool)
```

## Results

```{r}

```
